### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by cidadao** [renatosilva/colormake#2]
Hi,

Can you provide a better "guide" on how to use colormake under MSYS2?
Where should the Bash script be placed and how to create an alias?

Thanks

**Comment by renatosilva** [comment]
Hi Mario. You can place it under /usr/local/bin, and create an alias by adding `alias make=colormake` to you ~/.bashrc.

**Comment by renatosilva** [comment]
You can install the colormake package from my repository:

```
repman add renatosilva https://packages.renatosilva.me
pacman --sync colormake
```

This should colorize calls to make automatically. Aliases for other programs can be added to your `~/.bashrc`:

``` bash
alias gcc='COLORMAKE_COMMAND=gcc colormake'
alias clang='COLORMAKE_COMMAND=clang colormake'
```
